"""Every results file says what produced it, and the saying is checked.

A results file used to carry a bare ``git_commit``, which is a claim nothing
could test: the field keeps whatever value it was written with while the code
that produced the file goes on changing.  Six of the seven files that carried
one recorded a commit older than the last change to their own producer, and the
numbers in them were in fact still right -- but nothing in the repository could
have told a reader that, which is the same position as nothing being right.

Two rules replace it:

  a file that can be regenerated in a session carries a ``provenance`` block
  naming every source file its numbers depend on, with that file's digest.  If
  a producer changes, the digest no longer matches and the only way back to a
  passing suite is to regenerate the result.

  a file that cannot be regenerated in a session -- a training run, a re-score
  of 43,725 tracings, a corpus that is not in the repository -- is named here
  with the reason.  The set of such files is asserted, so a new results file
  cannot join them silently.
"""

from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

from ecs.provenance import REPO_ROOT, digest_of

RESULTS = REPO_ROOT / "results"

# Regenerated by a script that reads only committed files, in seconds to minutes.
REGENERABLE = (
    "abstention.json",
    "auxiliary.json",
    "outcomes.json",
    "perturbations.json",
    "shift.json",
    "subgroups.json",
)

# Not regenerable in a session, and why. The reason is the point: it is what a
# reader needs in order to judge how much the recorded commit is worth.
NOT_REGENERABLE = {
    "arms.json": "needs the five encoders' embeddings re-extracted over all three corpora",
    "baseline.json": "a 2 h 38 training run of the supervised baseline",
    "baseline/config.json": "written by that same training run",
    "baseline/metrics.json": "written by that same training run",
    "external/acs.json": "a re-score of 17,955 tracings from the raw waveforms",
    "external/sph.json": "a re-score of 25,770 tracings from the raw waveforms",
    "ingest_report.json": "a full re-read of all three corpora, 40 minutes",
    "seen_target.json": "needs the PhysioNet Challenge-2021 bundle, 21 GB, not in this repository",
    # The rotation's tables. Each needs the five corpora on disk, so none of
    # them regenerates from what this repository carries. What guards them
    # against the drift this registry exists to catch is a different check:
    # test_rotation.py compares the split sizes the table recorded against the
    # ones the code draws now, which is the way they went stale in practice.
    "label_map.json": "needs the Challenge-2021 bundle, PTB-XL and Shandong on disk",
    "duplicate_groups.json": (
        "a full re-read of the five rotation corpora, 1,221 s by its own seconds field"
    ),
    "split_leak.json": "needs the five corpora on disk to draw the splits it counts across",
    "rotation.json": (
        "needs the five corpora and the five trained models; the table alone is 416 s"
    ),
    "rotation_uncertainty.json": "written by the same chain as rotation.json",
    # The two grids the summaries above are read from. A CSV carries no
    # provenance block, so without a row here they sat outside the registry
    # while the files they summarise sat inside it.
    "rotation.csv": ("the 2,520-cell grid rotation.json summarises, written by the same 416 s run"),
    "rotation_uncertainty.csv": (
        "the 1,624-row grid rotation_uncertainty.json summarises, written by the same run"
    ),
    "target_scale.json": "needs PTB-XL and Chongqing on disk to draw the ladder's splits",
    "rotation/chapman_ningbo/config.json": "written by a training run of that source",
    "rotation/chapman_ningbo/metrics.json": "written by that same training run",
    "rotation/cpsc/config.json": "written by a training run of that source",
    "rotation/cpsc/metrics.json": "written by that same training run",
    "rotation/georgia/config.json": "written by a training run of that source",
    "rotation/georgia/metrics.json": "written by that same training run",
    "rotation/ptbxl/config.json": "written by a training run of that source",
    "rotation/ptbxl/metrics.json": "written by that same training run",
    "rotation/sph/config.json": "written by a training run of that source",
    "rotation/sph/metrics.json": "written by that same training run",
    "timing.json": "a measurement of one machine at one moment",
    "timing_esprimo.json": "a measurement of a second machine at one moment",
}


def tracked_tables() -> list[str]:
    """Every committed results table, excluding the per-encoder and figure sidecars.

    CSV counts as a table.  Restricting this to JSON let the two rotation grids
    sit outside the registry while the summaries computed from them sat inside
    it, which is the drift the registry exists to catch.
    """
    listed = subprocess.run(
        ["git", "ls-files", "results"], capture_output=True, text=True, check=True, cwd=REPO_ROOT
    ).stdout.split()
    return sorted(
        path[len("results/") :]
        for path in listed
        if path.endswith((".json", ".csv"))
        and not path.startswith("results/embeddings/")
        and not path.startswith("results/figures/")
    )


def commit_is_known(commit: str) -> bool:
    """Whether this checkout holds the commit; a shallow CI clone may not."""
    return (
        subprocess.run(
            ["git", "cat-file", "-e", f"{commit}^{{commit}}"],
            capture_output=True,
            cwd=REPO_ROOT,
        ).returncode
        == 0
    )


class TestRegenerableFilesRecordTheirProducers:
    @pytest.mark.parametrize("name", REGENERABLE)
    def test_every_recorded_producer_still_has_its_recorded_digest(self, name: str) -> None:
        block = json.loads((RESULTS / name).read_text())["provenance"]
        assert block["producers"], f"{name} records no producer"
        for path, recorded in block["producers"].items():
            source = REPO_ROOT / path
            assert source.is_file(), f"{name} names a producer that is gone: {path}"
            assert digest_of(source) == recorded, (
                f"{path} has changed since {name} was written; regenerate it"
            )

    @pytest.mark.parametrize("name", REGENERABLE)
    def test_the_producers_include_the_script_that_writes_the_file(self, name: str) -> None:
        """A block that omits its own script would pass while the script drifts."""
        block = json.loads((RESULTS / name).read_text())["provenance"]
        stem = Path(name).stem
        expected = {"shift": "shift_table", "abstention": "abstention_table"}.get(stem, stem)
        assert f"scripts/{expected}.py" in block["producers"]

    @pytest.mark.parametrize("name", REGENERABLE)
    def test_the_recorded_commit_is_an_ancestor_of_this_one(self, name: str) -> None:
        commit = json.loads((RESULTS / name).read_text())["provenance"]["commit"]
        assert commit, f"{name} records no commit"
        if not commit_is_known(commit):
            pytest.skip("shallow checkout: the recorded commit is not in this clone")
        assert (
            subprocess.run(
                ["git", "merge-base", "--is-ancestor", commit, "HEAD"],
                capture_output=True,
                cwd=REPO_ROOT,
            ).returncode
            == 0
        ), f"{name} records {commit[:7]}, which is not an ancestor of HEAD"


class TestNothingIsUnaccountedFor:
    def test_every_committed_table_is_either_regenerable_or_excused(self) -> None:
        accounted = set(REGENERABLE) | set(NOT_REGENERABLE)
        assert set(tracked_tables()) == accounted, (
            "a results file has appeared or gone: add it to REGENERABLE with a provenance "
            "block, or to NOT_REGENERABLE with the reason it cannot be regenerated"
        )

    @pytest.mark.parametrize("name", sorted(NOT_REGENERABLE))
    def test_an_excused_file_carries_no_provenance_block_it_cannot_honour(self, name: str) -> None:
        """The excuse and the block are alternatives; carrying both would hide drift.

        A CSV has nowhere to put a block, which is the reason its row here is
        the only thing standing between it and going unaccounted for.
        """
        if name.endswith(".csv"):
            pytest.skip("a CSV carries no provenance block")
        assert "provenance" not in json.loads((RESULTS / name).read_text())

    @pytest.mark.parametrize("name", sorted(NOT_REGENERABLE))
    def test_the_reason_is_a_reason(self, name: str) -> None:
        assert len(NOT_REGENERABLE[name]) > 20


def test_a_changed_producer_would_be_caught(tmp_path: Path) -> None:
    """The check bites: one byte moved in a producer breaks the comparison."""
    block = json.loads((RESULTS / "outcomes.json").read_text())["provenance"]
    path, recorded = next(iter(block["producers"].items()))
    tampered = tmp_path / "tampered.py"
    tampered.write_bytes((REPO_ROOT / path).read_bytes() + b"\n# one more line\n")
    assert digest_of(tampered) != recorded
